### ISSUE TITLE
Refactoring: API module

### ISSUE THREAD

**Issue by yoonlight** [kw-kwix/kwix-web#19]
### issue
API request module 역할 별로 묶어주기

### why
API request 모듈의 역할 불 명확

### test
API 서버와 통신 정상 작동 여부 확인

### todo
- [x] 각 역할에 맡게 API를 모아주기
- [x] 컴포넌트에 변경 사항 적용
- [x] 서버와 연동 테스트
